services:
  - type: web
    name: donet-supervision-system
    runtime: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: APP_NAME
        value: DONET
      - key: APP_VERSION
        value: "1.0"
      - key: ENVIRONMENT
        value: production
      - key: NODE_ENV
        value: production
